<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
      <TargetFrameworks>net8.0</TargetFrameworks>
      <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <PropertyGroup>
    <AssemblyName>Aspire.ManifestBridge</AssemblyName>
    <RootNamespace>Aspire.ManifestBridge</RootNamespace>
  </PropertyGroup>
</Project>