using JocysCom.VS.AiCompanion.Clients.OpenAI.Models;

public interface IClient
{
    create_chat_completion_function_response create_chat_completion(create_chat_completion_request body);
    create_chat_completion_function_response create_completion(create_completion_request body);
    create_edit_response create_edit(create_edit_request body);
    images_response create_image(create_image_request body);
    images_response create_image_edit(create_image_edit_request body);
    images_response create_image_variation(create_image_variation_request body);
    create_embedding_response create_embedding(create_embedding_request body);
    string create_speech(create_speech_request body);
    create_translation_response create_transcription(create_transcription_request body);
    create_translation_response create_translation(create_translation_request body);
    list_fine_tune_events_response list_files(string purpose);
    file create_file(create_file_request body);
    delete_assistant_file_response delete_file(string file_id);
    file retrieve_file(string file_id);
    string download_file(string file_id);
    fine_tuning_job create_fine_tuning_job(create_fine_tuning_job_request body);
    list_paginated_fine_tuning_jobs_response list_paginated_fine_tuning_jobs(string after, int limit);
    fine_tuning_job retrieve_fine_tuning_job(string fine_tuning_job_id);
    list_fine_tune_events_response list_fine_tuning_events(string fine_tuning_job_id, string after, int limit);
    fine_tuning_job cancel_fine_tuning_job(string fine_tuning_job_id);
    fine_tune create_fine_tune(create_fine_tune_request body);
    list_fine_tune_events_response list_fine_tunes();
    fine_tune retrieve_fine_tune(string fine_tune_id);
    fine_tune cancel_fine_tune(string fine_tune_id);
    list_fine_tune_events_response list_fine_tune_events(string fine_tune_id, bool stream);
    list_fine_tune_events_response list_models();
    model retrieve_model(string model);
    delete_assistant_file_response delete_model(string model);
    create_moderation_response create_moderation(create_moderation_request body);
    list_runs_response list_assistants(int limit, string order, string after, string before);
    assistant_object create_assistant(modify_assistant_request body);
    assistant_object get_assistant(string assistant_id);
    assistant_object modify_assistant(string assistant_id, modify_assistant_request body);
    delete_assistant_file_response delete_assistant(string assistant_id);
    thread_object create_thread(create_thread_request body);
    thread_object get_thread(string thread_id);
    thread_object modify_thread(string thread_id, modify_message_request body);
    delete_assistant_file_response delete_thread(string thread_id);
    list_runs_response list_messages(string thread_id, int limit, string order, string after, string before);
    message_object create_message(string thread_id, create_message_request body);
    message_object get_message(string thread_id, string message_id);
    message_object modify_message(string thread_id, string message_id, modify_message_request body);
    run_object create_thread_and_run(create_thread_and_run_request body);
    list_runs_response list_runs(string thread_id, int limit, string order, string after, string before);
    run_object create_run(string thread_id, create_run_request body);
    run_object get_run(string thread_id, string run_id);
    run_object modify_run(string thread_id, string run_id, modify_message_request body);
    run_object submit_tool_ouputs_to_run(string thread_id, string run_id, submit_tool_outputs_run_request body);
    run_object cancel_run(string thread_id, string run_id);
    list_runs_response list_run_steps(string thread_id, string run_id, int limit, string order, string after, string before);
    run_step_object get_run_step(string thread_id, string run_id, string step_id);
    list_runs_response list_assistant_files(string assistant_id, int limit, string order, string after, string before);
    assistant_file_object create_assistant_file(string assistant_id, create_assistant_file_request body);
    assistant_file_object get_assistant_file(string assistant_id, string file_id);
    delete_assistant_file_response delete_assistant_file(string assistant_id, string file_id);
    list_runs_response list_message_files(string thread_id, string message_id, int limit, string order, string after, string before);
    message_file_object get_message_file(string thread_id, string message_id, string file_id);
}
