//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.SqlServer.Management.ConnectionUI {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SqlExpressConnectionUIControl {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SqlExpressConnectionUIControl() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.SqlServer.Management.ConnectionUI.SqlExpressConnectionUIControl", typeof(SqlExpressConnectionUIControl).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.AnchorStyles similar to Left, Right.
        /// </summary>
        public static System.Windows.Forms.AnchorStyles browseButton_Anchor {
            get {
                object obj = ResourceManager.GetObject("browseButton.Anchor", resourceCulture);
                return ((System.Windows.Forms.AnchorStyles)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool browseButton_AutoSize {
            get {
                object obj = ResourceManager.GetObject("browseButton.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.FlatStyle similar to System.
        /// </summary>
        public static System.Windows.Forms.FlatStyle browseButton_FlatStyle {
            get {
                object obj = ResourceManager.GetObject("browseButton.FlatStyle", resourceCulture);
                return ((System.Windows.Forms.FlatStyle)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=225,Y=0}.
        /// </summary>
        public static System.Drawing.Point browseButton_Location {
            get {
                object obj = ResourceManager.GetObject("browseButton.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.Padding similar to {Left=3,Top=0,Right=0,Bottom=0}.
        /// </summary>
        public static System.Windows.Forms.Padding browseButton_Margin {
            get {
                object obj = ResourceManager.GetObject("browseButton.Margin", resourceCulture);
                return ((System.Windows.Forms.Padding)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=75, Height=23}.
        /// </summary>
        public static System.Drawing.Size browseButton_Size {
            get {
                object obj = ResourceManager.GetObject("browseButton.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 1.
        /// </summary>
        public static int browseButton_TabIndex {
            get {
                object obj = ResourceManager.GetObject("browseButton.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Browse....
        /// </summary>
        public static string browseButton_Text {
            get {
                return ResourceManager.GetString("browseButton.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool databaseFileLabel_AutoSize {
            get {
                object obj = ResourceManager.GetObject("databaseFileLabel.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=0,Y=0}.
        /// </summary>
        public static System.Drawing.Point databaseFileLabel_Location {
            get {
                object obj = ResourceManager.GetObject("databaseFileLabel.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.Padding similar to {Left=0,Top=0,Right=0,Bottom=0}.
        /// </summary>
        public static System.Windows.Forms.Padding databaseFileLabel_Margin {
            get {
                object obj = ResourceManager.GetObject("databaseFileLabel.Margin", resourceCulture);
                return ((System.Windows.Forms.Padding)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=180, Height=13}.
        /// </summary>
        public static System.Drawing.Size databaseFileLabel_Size {
            get {
                object obj = ResourceManager.GetObject("databaseFileLabel.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 0.
        /// </summary>
        public static int databaseFileLabel_TabIndex {
            get {
                object obj = ResourceManager.GetObject("databaseFileLabel.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Database file name (new or existing):.
        /// </summary>
        public static string databaseFileLabel_Text {
            get {
                return ResourceManager.GetString("databaseFileLabel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.AnchorStyles similar to Top, Left, Right.
        /// </summary>
        public static System.Windows.Forms.AnchorStyles databaseFileTableLayoutPanel_Anchor {
            get {
                object obj = ResourceManager.GetObject("databaseFileTableLayoutPanel.Anchor", resourceCulture);
                return ((System.Windows.Forms.AnchorStyles)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool databaseFileTableLayoutPanel_AutoSize {
            get {
                object obj = ResourceManager.GetObject("databaseFileTableLayoutPanel.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 2.
        /// </summary>
        public static int databaseFileTableLayoutPanel_ColumnCount {
            get {
                object obj = ResourceManager.GetObject("databaseFileTableLayoutPanel.ColumnCount", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.TableLayoutSettings.
        /// </summary>
        public static System.Windows.Forms.TableLayoutSettings databaseFileTableLayoutPanel_LayoutSettings {
            get {
                object obj = ResourceManager.GetObject("databaseFileTableLayoutPanel.LayoutSettings", resourceCulture);
                return ((System.Windows.Forms.TableLayoutSettings)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=0,Y=16}.
        /// </summary>
        public static System.Drawing.Point databaseFileTableLayoutPanel_Location {
            get {
                object obj = ResourceManager.GetObject("databaseFileTableLayoutPanel.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.Padding similar to {Left=0,Top=3,Right=0,Bottom=3}.
        /// </summary>
        public static System.Windows.Forms.Padding databaseFileTableLayoutPanel_Margin {
            get {
                object obj = ResourceManager.GetObject("databaseFileTableLayoutPanel.Margin", resourceCulture);
                return ((System.Windows.Forms.Padding)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 1.
        /// </summary>
        public static int databaseFileTableLayoutPanel_RowCount {
            get {
                object obj = ResourceManager.GetObject("databaseFileTableLayoutPanel.RowCount", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=300, Height=23}.
        /// </summary>
        public static System.Drawing.Size databaseFileTableLayoutPanel_Size {
            get {
                object obj = ResourceManager.GetObject("databaseFileTableLayoutPanel.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 1.
        /// </summary>
        public static int databaseFileTableLayoutPanel_TabIndex {
            get {
                object obj = ResourceManager.GetObject("databaseFileTableLayoutPanel.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.AnchorStyles similar to Left, Right.
        /// </summary>
        public static System.Windows.Forms.AnchorStyles databaseFileTextBox_Anchor {
            get {
                object obj = ResourceManager.GetObject("databaseFileTextBox.Anchor", resourceCulture);
                return ((System.Windows.Forms.AnchorStyles)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=0,Y=1}.
        /// </summary>
        public static System.Drawing.Point databaseFileTextBox_Location {
            get {
                object obj = ResourceManager.GetObject("databaseFileTextBox.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.Padding similar to {Left=0,Top=0,Right=3,Bottom=0}.
        /// </summary>
        public static System.Windows.Forms.Padding databaseFileTextBox_Margin {
            get {
                object obj = ResourceManager.GetObject("databaseFileTextBox.Margin", resourceCulture);
                return ((System.Windows.Forms.Padding)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=219, Height=20}.
        /// </summary>
        public static System.Drawing.Size databaseFileTextBox_Size {
            get {
                object obj = ResourceManager.GetObject("databaseFileTextBox.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 0.
        /// </summary>
        public static int databaseFileTextBox_TabIndex {
            get {
                object obj = ResourceManager.GetObject("databaseFileTextBox.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.AnchorStyles similar to Top, Left, Right.
        /// </summary>
        public static System.Windows.Forms.AnchorStyles loginTableLayoutPanel_Anchor {
            get {
                object obj = ResourceManager.GetObject("loginTableLayoutPanel.Anchor", resourceCulture);
                return ((System.Windows.Forms.AnchorStyles)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool loginTableLayoutPanel_AutoSize {
            get {
                object obj = ResourceManager.GetObject("loginTableLayoutPanel.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 2.
        /// </summary>
        public static int loginTableLayoutPanel_ColumnCount {
            get {
                object obj = ResourceManager.GetObject("loginTableLayoutPanel.ColumnCount", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.TableLayoutSettings.
        /// </summary>
        public static System.Windows.Forms.TableLayoutSettings loginTableLayoutPanel_LayoutSettings {
            get {
                object obj = ResourceManager.GetObject("loginTableLayoutPanel.LayoutSettings", resourceCulture);
                return ((System.Windows.Forms.TableLayoutSettings)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=30,Y=64}.
        /// </summary>
        public static System.Drawing.Point loginTableLayoutPanel_Location {
            get {
                object obj = ResourceManager.GetObject("loginTableLayoutPanel.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.Padding similar to {Left=27,Top=0,Right=9,Bottom=9}.
        /// </summary>
        public static System.Windows.Forms.Padding loginTableLayoutPanel_Margin {
            get {
                object obj = ResourceManager.GetObject("loginTableLayoutPanel.Margin", resourceCulture);
                return ((System.Windows.Forms.Padding)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 3.
        /// </summary>
        public static int loginTableLayoutPanel_RowCount {
            get {
                object obj = ResourceManager.GetObject("loginTableLayoutPanel.RowCount", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=258, Height=70}.
        /// </summary>
        public static System.Drawing.Size loginTableLayoutPanel_Size {
            get {
                object obj = ResourceManager.GetObject("loginTableLayoutPanel.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 2.
        /// </summary>
        public static int loginTableLayoutPanel_TabIndex {
            get {
                object obj = ResourceManager.GetObject("loginTableLayoutPanel.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.AnchorStyles similar to Top, Left, Right.
        /// </summary>
        public static System.Windows.Forms.AnchorStyles logonGroupBox_Anchor {
            get {
                object obj = ResourceManager.GetObject("logonGroupBox.Anchor", resourceCulture);
                return ((System.Windows.Forms.AnchorStyles)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=0,Y=45}.
        /// </summary>
        public static System.Drawing.Point logonGroupBox_Location {
            get {
                object obj = ResourceManager.GetObject("logonGroupBox.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.Padding similar to {Left=0,Top=3,Right=0,Bottom=0}.
        /// </summary>
        public static System.Windows.Forms.Padding logonGroupBox_Margin {
            get {
                object obj = ResourceManager.GetObject("logonGroupBox.Margin", resourceCulture);
                return ((System.Windows.Forms.Padding)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=300, Height=146}.
        /// </summary>
        public static System.Drawing.Size logonGroupBox_Size {
            get {
                object obj = ResourceManager.GetObject("logonGroupBox.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 3.
        /// </summary>
        public static int logonGroupBox_TabIndex {
            get {
                object obj = ResourceManager.GetObject("logonGroupBox.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log on to the server.
        /// </summary>
        public static string logonGroupBox_Text {
            get {
                return ResourceManager.GetString("logonGroupBox.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.AnchorStyles similar to Left.
        /// </summary>
        public static System.Windows.Forms.AnchorStyles passwordLabel_Anchor {
            get {
                object obj = ResourceManager.GetObject("passwordLabel.Anchor", resourceCulture);
                return ((System.Windows.Forms.AnchorStyles)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool passwordLabel_AutoSize {
            get {
                object obj = ResourceManager.GetObject("passwordLabel.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=0,Y=32}.
        /// </summary>
        public static System.Drawing.Point passwordLabel_Location {
            get {
                object obj = ResourceManager.GetObject("passwordLabel.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.Padding similar to {Left=0,Top=0,Right=3,Bottom=0}.
        /// </summary>
        public static System.Windows.Forms.Padding passwordLabel_Margin {
            get {
                object obj = ResourceManager.GetObject("passwordLabel.Margin", resourceCulture);
                return ((System.Windows.Forms.Padding)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=56, Height=13}.
        /// </summary>
        public static System.Drawing.Size passwordLabel_Size {
            get {
                object obj = ResourceManager.GetObject("passwordLabel.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 2.
        /// </summary>
        public static int passwordLabel_TabIndex {
            get {
                object obj = ResourceManager.GetObject("passwordLabel.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Password:.
        /// </summary>
        public static string passwordLabel_Text {
            get {
                return ResourceManager.GetString("passwordLabel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.AnchorStyles similar to Left, Right.
        /// </summary>
        public static System.Windows.Forms.AnchorStyles passwordTextBox_Anchor {
            get {
                object obj = ResourceManager.GetObject("passwordTextBox.Anchor", resourceCulture);
                return ((System.Windows.Forms.AnchorStyles)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=67,Y=29}.
        /// </summary>
        public static System.Drawing.Point passwordTextBox_Location {
            get {
                object obj = ResourceManager.GetObject("passwordTextBox.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.Padding similar to {Left=3,Top=3,Right=0,Bottom=3}.
        /// </summary>
        public static System.Windows.Forms.Padding passwordTextBox_Margin {
            get {
                object obj = ResourceManager.GetObject("passwordTextBox.Margin", resourceCulture);
                return ((System.Windows.Forms.Padding)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Char similar to ●.
        /// </summary>
        public static char passwordTextBox_PasswordChar {
            get {
                object obj = ResourceManager.GetObject("passwordTextBox.PasswordChar", resourceCulture);
                return ((char)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=191, Height=20}.
        /// </summary>
        public static System.Drawing.Size passwordTextBox_Size {
            get {
                object obj = ResourceManager.GetObject("passwordTextBox.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 3.
        /// </summary>
        public static int passwordTextBox_TabIndex {
            get {
                object obj = ResourceManager.GetObject("passwordTextBox.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.AnchorStyles similar to Left.
        /// </summary>
        public static System.Windows.Forms.AnchorStyles savePasswordCheckBox_Anchor {
            get {
                object obj = ResourceManager.GetObject("savePasswordCheckBox.Anchor", resourceCulture);
                return ((System.Windows.Forms.AnchorStyles)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool savePasswordCheckBox_AutoSize {
            get {
                object obj = ResourceManager.GetObject("savePasswordCheckBox.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.FlatStyle similar to System.
        /// </summary>
        public static System.Windows.Forms.FlatStyle savePasswordCheckBox_FlatStyle {
            get {
                object obj = ResourceManager.GetObject("savePasswordCheckBox.FlatStyle", resourceCulture);
                return ((System.Windows.Forms.FlatStyle)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=67,Y=52}.
        /// </summary>
        public static System.Drawing.Point savePasswordCheckBox_Location {
            get {
                object obj = ResourceManager.GetObject("savePasswordCheckBox.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.Padding similar to {Left=3,Top=0,Right=0,Bottom=0}.
        /// </summary>
        public static System.Windows.Forms.Padding savePasswordCheckBox_Margin {
            get {
                object obj = ResourceManager.GetObject("savePasswordCheckBox.Margin", resourceCulture);
                return ((System.Windows.Forms.Padding)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=121, Height=18}.
        /// </summary>
        public static System.Drawing.Size savePasswordCheckBox_Size {
            get {
                object obj = ResourceManager.GetObject("savePasswordCheckBox.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 5.
        /// </summary>
        public static int savePasswordCheckBox_TabIndex {
            get {
                object obj = ResourceManager.GetObject("savePasswordCheckBox.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Save my password.
        /// </summary>
        public static string savePasswordCheckBox_Text {
            get {
                return ResourceManager.GetString("savePasswordCheckBox.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool sqlAuthenticationRadioButton_AutoSize {
            get {
                object obj = ResourceManager.GetObject("sqlAuthenticationRadioButton.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.FlatStyle similar to System.
        /// </summary>
        public static System.Windows.Forms.FlatStyle sqlAuthenticationRadioButton_FlatStyle {
            get {
                object obj = ResourceManager.GetObject("sqlAuthenticationRadioButton.FlatStyle", resourceCulture);
                return ((System.Windows.Forms.FlatStyle)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=12,Y=46}.
        /// </summary>
        public static System.Drawing.Point sqlAuthenticationRadioButton_Location {
            get {
                object obj = ResourceManager.GetObject("sqlAuthenticationRadioButton.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.Padding similar to {Left=9,Top=3,Right=9,Bottom=0}.
        /// </summary>
        public static System.Windows.Forms.Padding sqlAuthenticationRadioButton_Margin {
            get {
                object obj = ResourceManager.GetObject("sqlAuthenticationRadioButton.Margin", resourceCulture);
                return ((System.Windows.Forms.Padding)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=179, Height=18}.
        /// </summary>
        public static System.Drawing.Size sqlAuthenticationRadioButton_Size {
            get {
                object obj = ResourceManager.GetObject("sqlAuthenticationRadioButton.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 1.
        /// </summary>
        public static int sqlAuthenticationRadioButton_TabIndex {
            get {
                object obj = ResourceManager.GetObject("sqlAuthenticationRadioButton.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use S&amp;QL Server Authentication.
        /// </summary>
        public static string sqlAuthenticationRadioButton_Text {
            get {
                return ResourceManager.GetString("sqlAuthenticationRadioButton.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.AnchorStyles similar to Left.
        /// </summary>
        public static System.Windows.Forms.AnchorStyles userNameLabel_Anchor {
            get {
                object obj = ResourceManager.GetObject("userNameLabel.Anchor", resourceCulture);
                return ((System.Windows.Forms.AnchorStyles)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool userNameLabel_AutoSize {
            get {
                object obj = ResourceManager.GetObject("userNameLabel.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=0,Y=6}.
        /// </summary>
        public static System.Drawing.Point userNameLabel_Location {
            get {
                object obj = ResourceManager.GetObject("userNameLabel.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.Padding similar to {Left=0,Top=0,Right=3,Bottom=0}.
        /// </summary>
        public static System.Windows.Forms.Padding userNameLabel_Margin {
            get {
                object obj = ResourceManager.GetObject("userNameLabel.Margin", resourceCulture);
                return ((System.Windows.Forms.Padding)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=61, Height=13}.
        /// </summary>
        public static System.Drawing.Size userNameLabel_Size {
            get {
                object obj = ResourceManager.GetObject("userNameLabel.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 0.
        /// </summary>
        public static int userNameLabel_TabIndex {
            get {
                object obj = ResourceManager.GetObject("userNameLabel.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;User name:.
        /// </summary>
        public static string userNameLabel_Text {
            get {
                return ResourceManager.GetString("userNameLabel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.AnchorStyles similar to Left, Right.
        /// </summary>
        public static System.Windows.Forms.AnchorStyles userNameTextBox_Anchor {
            get {
                object obj = ResourceManager.GetObject("userNameTextBox.Anchor", resourceCulture);
                return ((System.Windows.Forms.AnchorStyles)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=67,Y=3}.
        /// </summary>
        public static System.Drawing.Point userNameTextBox_Location {
            get {
                object obj = ResourceManager.GetObject("userNameTextBox.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.Padding similar to {Left=3,Top=3,Right=0,Bottom=3}.
        /// </summary>
        public static System.Windows.Forms.Padding userNameTextBox_Margin {
            get {
                object obj = ResourceManager.GetObject("userNameTextBox.Margin", resourceCulture);
                return ((System.Windows.Forms.Padding)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 128.
        /// </summary>
        public static int userNameTextBox_MaxLength {
            get {
                object obj = ResourceManager.GetObject("userNameTextBox.MaxLength", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=191, Height=20}.
        /// </summary>
        public static System.Drawing.Size userNameTextBox_Size {
            get {
                object obj = ResourceManager.GetObject("userNameTextBox.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 1.
        /// </summary>
        public static int userNameTextBox_TabIndex {
            get {
                object obj = ResourceManager.GetObject("userNameTextBox.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool windowsAuthenticationRadioButton_AutoSize {
            get {
                object obj = ResourceManager.GetObject("windowsAuthenticationRadioButton.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.FlatStyle similar to System.
        /// </summary>
        public static System.Windows.Forms.FlatStyle windowsAuthenticationRadioButton_FlatStyle {
            get {
                object obj = ResourceManager.GetObject("windowsAuthenticationRadioButton.FlatStyle", resourceCulture);
                return ((System.Windows.Forms.FlatStyle)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=12,Y=25}.
        /// </summary>
        public static System.Drawing.Point windowsAuthenticationRadioButton_Location {
            get {
                object obj = ResourceManager.GetObject("windowsAuthenticationRadioButton.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.Padding similar to {Left=9,Top=9,Right=9,Bottom=0}.
        /// </summary>
        public static System.Windows.Forms.Padding windowsAuthenticationRadioButton_Margin {
            get {
                object obj = ResourceManager.GetObject("windowsAuthenticationRadioButton.Margin", resourceCulture);
                return ((System.Windows.Forms.Padding)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=168, Height=18}.
        /// </summary>
        public static System.Drawing.Size windowsAuthenticationRadioButton_Size {
            get {
                object obj = ResourceManager.GetObject("windowsAuthenticationRadioButton.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 0.
        /// </summary>
        public static int windowsAuthenticationRadioButton_TabIndex {
            get {
                object obj = ResourceManager.GetObject("windowsAuthenticationRadioButton.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use &amp;Windows Authentication.
        /// </summary>
        public static string windowsAuthenticationRadioButton_Text {
            get {
                return ResourceManager.GetString("windowsAuthenticationRadioButton.Text", resourceCulture);
            }
        }
    }
}
