trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  ARM_CLIENT_ID: '$(armClientId)'
  ARM_CLIENT_SECRET: '$(armClientSecret)'
  ARM_TENANT_ID: '$(armTenantId)'
  ARM_SUBSCRIPTION_ID: '$(armSubscriptionId)'

steps:
- script: |
    $modules = @('Az', 'SqlServer')
    foreach ($module in $modules) {
        if (-not (Get-Module -Name $module -ListAvailable)) {
            Install-Module -Name $module -Force -Scope CurrentUser
        }
        else {
            Update-Module -Name $module
        }
    }
  displayName: 'Install PowerShell Modules'
  pwsh: true

- script: |
    terraform init
    terraform apply -auto-approve
  displayName: 'Run Terraform'
  env:
    ARM_CLIENT_ID: $(ARM_CLIENT_ID)
    ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
    ARM_TENANT_ID: $(ARM_TENANT_ID)
    ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
  pwsh: true