//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JocysCom.VS.AiCompanion.Engine.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JocysCom.VS.AiCompanion.Engine.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Assistants.
        /// </summary>
        public static string _1_Assistants {
            get {
                return ResourceManager.GetString("_1_Assistants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Source Files.
        /// </summary>
        public static string _1_Source_Files {
            get {
                return ResourceManager.GetString("_1_Source_Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. Tuning Files.
        /// </summary>
        public static string _2_Tuning_Files {
            get {
                return ResourceManager.GetString("_2_Tuning_Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3. Remote Files.
        /// </summary>
        public static string _3_Remote_Files {
            get {
                return ResourceManager.GetString("_3_Remote_Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4. Tuning Jobs.
        /// </summary>
        public static string _4_Tuning_Jobs {
            get {
                return ResourceManager.GetString("_4_Tuning_Jobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5. Models.
        /// </summary>
        public static string _5_Models {
            get {
                return ResourceManager.GetString("_5_Models", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add....
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New.
        /// </summary>
        public static string Add_New {
            get {
                return ResourceManager.GetString("Add_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AI API Services.
        /// </summary>
        public static string AI_API_Services {
            get {
                return ResourceManager.GetString("AI_API_Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow Only One Copy.
        /// </summary>
        public static string Allow_Only_One_Copy {
            get {
                return ResourceManager.GetString("Allow_Only_One_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API Base URL.
        /// </summary>
        public static string API_Base_URL {
            get {
                return ResourceManager.GetString("API_Base_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API Key.
        /// </summary>
        public static string API_Key {
            get {
                return ResourceManager.GetString("API_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API Organization ID.
        /// </summary>
        public static string API_Organization_ID {
            get {
                return ResourceManager.GetString("API_Organization_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Always on Top.
        /// </summary>
        public static string App_Always_on_Top {
            get {
                return ResourceManager.GetString("App_Always_on_Top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approval Template.
        /// </summary>
        public static string Approval_Template {
            get {
                return ResourceManager.GetString("Approval_Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approval.
        /// </summary>
        public static string Approval_Type {
            get {
                return ResourceManager.GetString("Approval_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachments.
        /// </summary>
        public static string Attachments {
            get {
                return ResourceManager.GetString("Attachments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-Generate Title.
        /// </summary>
        public static string Auto_Generate_Title {
            get {
                return ResourceManager.GetString("Auto_Generate_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Markdown.
        /// </summary>
        public static string Auto_Markdown {
            get {
                return ResourceManager.GetString("Auto_Markdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automation.
        /// </summary>
        public static string Automation {
            get {
                return ResourceManager.GetString("Automation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Axialis Icon Set Licenses.
        /// </summary>
        public static string Axialis_Icon_Set_Licenses {
            get {
                return ResourceManager.GetString("Axialis_Icon_Set_Licenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bar Always on Top.
        /// </summary>
        public static string Bar_Always_on_Top {
            get {
                return ResourceManager.GetString("Bar_Always_on_Top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bytes.
        /// </summary>
        public static string Bytes {
            get {
                return ResourceManager.GetString("Bytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request to call the function was denied!.
        /// </summary>
        public static string Call_function_request_denied {
            get {
                return ResourceManager.GetString("Call_function_request_denied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Job.
        /// </summary>
        public static string Cancel_Job {
            get {
                return ResourceManager.GetString("Cancel_Job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes.
        /// </summary>
        public static string Changes {
            get {
                return ResourceManager.GetString("Changes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat.
        /// </summary>
        public static string Chat {
            get {
                return ResourceManager.GetString("Chat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat_Instructions .
        /// </summary>
        public static string Chat_Instructions {
            get {
                return ResourceManager.GetString("Chat_Instructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Product.
        /// </summary>
        public static string Company_Product {
            get {
                return ResourceManager.GetString("Company_Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy: Id, File Name.
        /// </summary>
        public static string Copy_Id_File_Name {
            get {
                return ResourceManager.GetString("Copy_Id_File_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy with Headers.
        /// </summary>
        public static string Copy_with_Headers {
            get {
                return ResourceManager.GetString("Copy_with_Headers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a Job and Model from File.
        /// </summary>
        public static string Create_a_Job_and_Model_from_File {
            get {
                return ResourceManager.GetString("Create_a_Job_and_Model_from_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create an Assistant Task from Model.
        /// </summary>
        public static string Create_an_Assistant_Task_from_Model {
            get {
                return ResourceManager.GetString("Create_an_Assistant_Task_from_Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        public static string Created {
            get {
                return ResourceManager.GetString("Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creativity.
        /// </summary>
        public static string Creativity {
            get {
                return ResourceManager.GetString("Creativity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        public static string Data {
            get {
                return ResourceManager.GetString("Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Folder.
        /// </summary>
        public static string Data_Folder {
            get {
                return ResourceManager.GetString("Data_Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default AI Model.
        /// </summary>
        public static string Default_AI_Model {
            get {
                return ResourceManager.GetString("Default_AI_Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable All.
        /// </summary>
        public static string Disable_All {
            get {
                return ResourceManager.GetString("Disable_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document.
        /// </summary>
        public static string Document {
            get {
                return ResourceManager.GetString("Document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable All.
        /// </summary>
        public static string Enable_All {
            get {
                return ResourceManager.GetString("Enable_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Low Risk.
        /// </summary>
        public static string Enable_Low_Risk {
            get {
                return ResourceManager.GetString("Enable_Low_Risk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Medium Risk.
        /// </summary>
        public static string Enable_Medium_Risk {
            get {
                return ResourceManager.GetString("Enable_Medium_Risk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable spell check for the chat textbox and certain option text boxes. IMPORTANT: Can slow down the app..
        /// </summary>
        public static string Enable_spell_check_for_the_chat_textbox {
            get {
                return ResourceManager.GetString("Enable_spell_check_for_the_chat_textbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Environment.
        /// </summary>
        public static string Environment {
            get {
                return ResourceManager.GetString("Environment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Name.
        /// </summary>
        public static string File_Name {
            get {
                return ResourceManager.GetString("File_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files.
        /// </summary>
        public static string Files {
            get {
                return ResourceManager.GetString("Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format Code.
        /// </summary>
        public static string Format_Code {
            get {
                return ResourceManager.GetString("Format_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GitHub Project.
        /// </summary>
        public static string GitHub_Project {
            get {
                return ResourceManager.GetString("GitHub_Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IconExperience License.
        /// </summary>
        public static string IconExperience_License {
            get {
                return ResourceManager.GetString("IconExperience_License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instructions.
        /// </summary>
        public static string Instructions {
            get {
                return ResourceManager.GetString("Instructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Azure OpenAI.
        /// </summary>
        public static string Is_Azure_OpenAI {
            get {
                return ResourceManager.GetString("Is_Azure_OpenAI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Default AI Service.
        /// </summary>
        public static string Is_Default_AI_Service {
            get {
                return ResourceManager.GetString("Is_Default_AI_Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jocys.com.
        /// </summary>
        public static string Jocys_com_Label {
            get {
                return ResourceManager.GetString("Jocys_com_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key.
        /// </summary>
        public static string Key {
            get {
                return ResourceManager.GetString("Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License.
        /// </summary>
        public static string License {
            get {
                return ResourceManager.GetString("License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description of the list for user information purposes only.
        /// </summary>
        public static string List_Description {
            get {
                return ResourceManager.GetString("List_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AI instructions that will be sent with this list..
        /// </summary>
        public static string List_Instructions {
            get {
                return ResourceManager.GetString("List_Instructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow to send this list to AI..
        /// </summary>
        public static string List_IsEnabled {
            get {
                return ResourceManager.GetString("List_IsEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prevent AI from modifying this list..
        /// </summary>
        public static string List_IsReadOnly {
            get {
                return ResourceManager.GetString("List_IsReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lists allow you to personalize interactions and ensure more relevant, context-aware responses, which greatly improves the user experience. AI can also manage different types of lists, such as task lists, to-do lists, progress tracking, and completion lists..
        /// </summary>
        public static string Lists_Feature_Description {
            get {
                return ResourceManager.GetString("Lists_Feature_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Market Place.
        /// </summary>
        public static string Market_Place {
            get {
                return ResourceManager.GetString("Market_Place", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Risk Level.
        /// </summary>
        public static string Maximum_Risk_Level {
            get {
                return ResourceManager.GetString("Maximum_Risk_Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize on Close.
        /// </summary>
        public static string Minimize_on_Close {
            get {
                return ResourceManager.GetString("Minimize_on_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize to Tray.
        /// </summary>
        public static string Minimize_to_Tray {
            get {
                return ResourceManager.GetString("Minimize_to_Tray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model.
        /// </summary>
        public static string Model {
            get {
                return ResourceManager.GetString("Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model Filter.
        /// </summary>
        public static string Model_Filter {
            get {
                return ResourceManager.GetString("Model_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to refresh models. Use CTRL+Click to set manually..
        /// </summary>
        public static string ModelRefreshButton_ToolTip {
            get {
                return ResourceManager.GetString("ModelRefreshButton_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object.
        /// </summary>
        public static string Object {
            get {
                return ResourceManager.GetString("Object", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open....
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open File.
        /// </summary>
        public static string Open_File {
            get {
                return ResourceManager.GetString("Open_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner.
        /// </summary>
        public static string Owner {
            get {
                return ResourceManager.GetString("Owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        public static string Paste {
            get {
                return ResourceManager.GetString("Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        public static string Path {
            get {
                return ResourceManager.GetString("Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        public static string Preview {
            get {
                return ResourceManager.GetString("Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prompting.
        /// </summary>
        public static string Prompting {
            get {
                return ResourceManager.GetString("Prompting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purpose.
        /// </summary>
        public static string Purpose {
            get {
                return ResourceManager.GetString("Purpose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove on Complete.
        /// </summary>
        public static string Remove_on_Complete {
            get {
                return ResourceManager.GetString("Remove_on_Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Application Settings.
        /// </summary>
        public static string Reset_Application_Settings {
            get {
                return ResourceManager.GetString("Reset_Application_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Prompting Settings.
        /// </summary>
        public static string Reset_Prompting_Settings {
            get {
                return ResourceManager.GetString("Reset_Prompting_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Settings.
        /// </summary>
        public static string Reset_Settings {
            get {
                return ResourceManager.GetString("Reset_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Templates Settings.
        /// </summary>
        public static string Reset_Templates_Settings {
            get {
                return ResourceManager.GetString("Reset_Templates_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset to Default.
        /// </summary>
        public static string Reset_to_Default {
            get {
                return ResourceManager.GetString("Reset_to_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response Streaming.
        /// </summary>
        public static string Response_Streaming {
            get {
                return ResourceManager.GetString("Response_Streaming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response Timeout.
        /// </summary>
        public static string Response_Timeout {
            get {
                return ResourceManager.GetString("Response_Timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search the list.
        /// </summary>
        public static string Search_the_list {
            get {
                return ResourceManager.GetString("Search_the_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selection.
        /// </summary>
        public static string Selection {
            get {
                return ResourceManager.GetString("Selection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send as System Messages.
        /// </summary>
        public static string Send_as_System_Messages {
            get {
                return ResourceManager.GetString("Send_as_System_Messages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Chat History.
        /// </summary>
        public static string Send_Chat_History {
            get {
                return ResourceManager.GetString("Send_Chat_History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send on Create.
        /// </summary>
        public static string Send_on_Create {
            get {
                return ResourceManager.GetString("Send_on_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending Message.
        /// </summary>
        public static string Sending_Message {
            get {
                return ResourceManager.GetString("Sending_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service.
        /// </summary>
        public static string Service {
            get {
                return ResourceManager.GetString("Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings Folder.
        /// </summary>
        public static string Settings_Folder {
            get {
                return ResourceManager.GetString("Settings_Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Documents Attached Warning.
        /// </summary>
        public static string Show_Documents_Attached_Warning {
            get {
                return ResourceManager.GetString("Show_Documents_Attached_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Icon in Toolbar.
        /// </summary>
        public static string Show_Icon_in_Toolbar {
            get {
                return ResourceManager.GetString("Show_Icon_in_Toolbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Instructions.
        /// </summary>
        public static string Show_Instructions {
            get {
                return ResourceManager.GetString("Show_Instructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Prompting.
        /// </summary>
        public static string Show_Prompting {
            get {
                return ResourceManager.GetString("Show_Prompting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Sensitive Data Warning.
        /// </summary>
        public static string Show_Sensitive_Data_Warning {
            get {
                return ResourceManager.GetString("Show_Sensitive_Data_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spell Check.
        /// </summary>
        public static string Spell_Check {
            get {
                return ResourceManager.GetString("Spell_Check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standalone Program.
        /// </summary>
        public static string Standalone_Program {
            get {
                return ResourceManager.GetString("Standalone_Program", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start with Windows.
        /// </summary>
        public static string Start_with_Windows {
            get {
                return ResourceManager.GetString("Start_with_Windows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Message.
        /// </summary>
        public static string System_Message {
            get {
                return ResourceManager.GetString("System_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Templates.
        /// </summary>
        public static string Templates {
            get {
                return ResourceManager.GetString("Templates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title for Attached Context.
        /// </summary>
        public static string Title_for_Attached_Context {
            get {
                return ResourceManager.GetString("Title_for_Attached_Context", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        public static string Upload {
            get {
                return ResourceManager.GetString("Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use [Enter] to send the message.
        /// </summary>
        public static string Use_Enter_to_send_the_message {
            get {
                return ResourceManager.GetString("Use_Enter_to_send_the_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Macros.
        /// </summary>
        public static string Use_Macros {
            get {
                return ResourceManager.GetString("Use_Macros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Maximum Context.
        /// </summary>
        public static string Use_Maximum_Context {
            get {
                return ResourceManager.GetString("Use_Maximum_Context", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validate.
        /// </summary>
        public static string Validate {
            get {
                return ResourceManager.GetString("Validate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visual Studio Extension Options.
        /// </summary>
        public static string Visual_Studio_Extension_Options {
            get {
                return ResourceManager.GetString("Visual_Studio_Extension_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This feature is only available when the application is run as an extension in Visual Studio..
        /// </summary>
        public static string VsExtensionFeatureMessage {
            get {
                return ResourceManager.GetString("VsExtensionFeatureMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This extension requires Visual Studio 2022 version 17.9. Use the Visual Studio Installer to update..
        /// </summary>
        public static string VsExtensionVersionMessage {
            get {
                return ResourceManager.GetString("VsExtensionVersionMessage", resourceCulture);
            }
        }
    }
}
