//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JocysCom.VS.AiCompanion.Engine.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JocysCom.VS.AiCompanion.Engine.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New.
        /// </summary>
        public static string Add_New {
            get {
                return ResourceManager.GetString("Add_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Assistants.
        /// </summary>
        public static string Assistants {
            get {
                return ResourceManager.GetString("Assistants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Axialis Icon Set Licenses.
        /// </summary>
        public static string Axialis_Icon_Set_Licenses {
            get {
                return ResourceManager.GetString("Axialis_Icon_Set_Licenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes.
        /// </summary>
        public static string Changes {
            get {
                return ResourceManager.GetString("Changes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Product.
        /// </summary>
        public static string Company_Product {
            get {
                return ResourceManager.GetString("Company_Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Folder.
        /// </summary>
        public static string Data_Folder {
            get {
                return ResourceManager.GetString("Data_Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default AI Model.
        /// </summary>
        public static string Default_AI_Model {
            get {
                return ResourceManager.GetString("Default_AI_Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GitHub Project.
        /// </summary>
        public static string GitHub_Project {
            get {
                return ResourceManager.GetString("GitHub_Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IconExperience License.
        /// </summary>
        public static string IconExperience_License {
            get {
                return ResourceManager.GetString("IconExperience_License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Azure OpenAI.
        /// </summary>
        public static string Is_Azure_OpenAI {
            get {
                return ResourceManager.GetString("Is_Azure_OpenAI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Default AI Service.
        /// </summary>
        public static string Is_Default_AI_Service {
            get {
                return ResourceManager.GetString("Is_Default_AI_Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jocys.com.
        /// </summary>
        public static string Jocys_com_Label {
            get {
                return ResourceManager.GetString("Jocys_com_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License.
        /// </summary>
        public static string License {
            get {
                return ResourceManager.GetString("License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Market Place.
        /// </summary>
        public static string Market_Place {
            get {
                return ResourceManager.GetString("Market_Place", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model.
        /// </summary>
        public static string Model {
            get {
                return ResourceManager.GetString("Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model Filter.
        /// </summary>
        public static string Model_Filter {
            get {
                return ResourceManager.GetString("Model_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to refresh models. Use CTRL+Click to set manually..
        /// </summary>
        public static string ModelRefreshButton_ToolTip {
            get {
                return ResourceManager.GetString("ModelRefreshButton_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open....
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open AI Base URL.
        /// </summary>
        public static string Open_AI_Base_URL {
            get {
                return ResourceManager.GetString("Open_AI_Base_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OpenAI API Key.
        /// </summary>
        public static string OpenAI_API_Key {
            get {
                return ResourceManager.GetString("OpenAI_API_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OpenAI API Organization ID.
        /// </summary>
        public static string OpenAI_API_Organization_ID {
            get {
                return ResourceManager.GetString("OpenAI_API_Organization_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response Streaming.
        /// </summary>
        public static string Response_Streaming {
            get {
                return ResourceManager.GetString("Response_Streaming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response Timeout.
        /// </summary>
        public static string Response_Timeout {
            get {
                return ResourceManager.GetString("Response_Timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service.
        /// </summary>
        public static string Service {
            get {
                return ResourceManager.GetString("Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Source Files.
        /// </summary>
        public static string Source_Files {
            get {
                return ResourceManager.GetString("Source_Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Message.
        /// </summary>
        public static string System_Message {
            get {
                return ResourceManager.GetString("System_Message", resourceCulture);
            }
        }
    }
}
